import type { Metadata } from "next";
import { Antic_Didone, Fira_Sans } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Image from "next/image";

const firaSans = Fira_Sans({
  variable: "--font-fira-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

const anticDidone = Antic_Didone({
  variable: "--font-antic-didone",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" relative">
        {children}
        <div className="w-[100%] top-0  fixed h-[100vh] grid place-items-center -z-10">
          <div className="w-[500px] h-[500px] relative ">
            <Image
              src="/logo.png"
              alt="echo-logo"
              className="opacity-15  pointer-events-none"
              fill
              sizes="500"
              priority
            />
          </div>
        </div>
      </body>
    </html>
  );
}
